/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NetworkCoordinator;

import Business.Network.Network;
import userinterface.Supplier.*;
import userinterface.Restaurant.*;
import Business.RawMaterial.RawMaterial;
import Business.RawMaterial.RawMaterialCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sachinsenthilkumar
 */
public class ManageRawMaterialsJPanel extends javax.swing.JPanel {

    private  JPanel userProcessContainer;

    private  RawMaterial rawmaterial;

    private Network network;
          /**
     * Creates new form ManageRawMaterialsJPanel
     */
   

    public ManageRawMaterialsJPanel(JPanel userProcessContainer, Network network) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
 
        this.network=network;
        populateTable();
    }
    
    public void populateTable() {                          //populate table
         DefaultTableModel dtm = (DefaultTableModel)tblRawMaterialList.getModel();
        dtm.setRowCount(0);
        
        try{
        for(RawMaterial rawmaterial : network.getRawMaterialcatalog().getRawMaterialList()){
            Object[] row = new Object[5];
            row[0] = rawmaterial;
            row[1] = rawmaterial.getMaterialId();
            row[2] = rawmaterial.getPrice();
            row[3] = rawmaterial.getType();

            
            dtm.addRow(row);
        }
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRawMaterialList = new javax.swing.JTable();
        txtRawMaterialID = new javax.swing.JTextField();
        btnSearchRawMaterial = new javax.swing.JButton();
        btnDeleteRawMaterial = new javax.swing.JButton();
        btnViewRawMaterial = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 51));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Manage Raw Materials");

        tblRawMaterialList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Material Name", "Material ID", "Material Price", "Material Type"
            }
        ));
        jScrollPane1.setViewportView(tblRawMaterialList);

        txtRawMaterialID.setText("Enter Raw Material ID HERE:");
        txtRawMaterialID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRawMaterialIDActionPerformed(evt);
            }
        });

        btnSearchRawMaterial.setBackground(new java.awt.Color(0, 0, 0));
        btnSearchRawMaterial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSearchRawMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchRawMaterial.setText("Search Raw Material");
        btnSearchRawMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchRawMaterialActionPerformed(evt);
            }
        });

        btnDeleteRawMaterial.setBackground(new java.awt.Color(0, 0, 0));
        btnDeleteRawMaterial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeleteRawMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteRawMaterial.setText("Delete Raw Material");
        btnDeleteRawMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRawMaterialActionPerformed(evt);
            }
        });

        btnViewRawMaterial.setBackground(new java.awt.Color(0, 0, 0));
        btnViewRawMaterial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnViewRawMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnViewRawMaterial.setText("View/Update Raw Material");
        btnViewRawMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRawMaterialActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(252, 252, 252)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRawMaterialID, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 487, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDeleteRawMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(btnSearchRawMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(btnViewRawMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(274, 274, 274))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRawMaterialID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchRawMaterial))
                .addGap(50, 50, 50)
                .addComponent(btnViewRawMaterial)
                .addGap(54, 54, 54)
                .addComponent(btnDeleteRawMaterial)
                .addGap(243, 243, 243))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRawMaterialIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRawMaterialIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRawMaterialIDActionPerformed

    private void btnSearchRawMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchRawMaterialActionPerformed
        // TODO add your handling code here:
        if(txtRawMaterialID.getText().equals("") || !(txtRawMaterialID.getText().matches("[0-9]+"))){
            JOptionPane.showMessageDialog(null,"Invalid Data");
        }
        else{
            int id= Integer.parseInt(txtRawMaterialID.getText());
            RawMaterial raw= network.getRawMaterialcatalog().searchRawMaterial(id);

            if(raw == null){
                JOptionPane.showMessageDialog(null, "RawMaterial Does Not Exist", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            else{

                SearchUpdateRawMaterialJPanel panel = new SearchUpdateRawMaterialJPanel(userProcessContainer, network, raw);
                userProcessContainer.add("SearchUpdateFoodItemPanel", panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);

                txtRawMaterialID.setText("Enter Raw Material ID Here");
            }

        }
    }//GEN-LAST:event_btnSearchRawMaterialActionPerformed

    private void btnDeleteRawMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRawMaterialActionPerformed
        // TODO add your handling code here:
        int row = tblRawMaterialList.getSelectedRow();

        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please Select a Row from the TABLE First", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to DELETE the Material?", "Warning", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            RawMaterial r= (RawMaterial)tblRawMaterialList.getValueAt(row, 0);
            network.getRawMaterialcatalog().deleteRawMaterial(r);
            populateTable();
        }
    }//GEN-LAST:event_btnDeleteRawMaterialActionPerformed

    private void btnViewRawMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRawMaterialActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblRawMaterialList.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please Select a Row from the TABLE to View Details", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            RawMaterial r= (RawMaterial)tblRawMaterialList.getValueAt(selectedRow, 0);
            SearchUpdateRawMaterialJPanel panel = new SearchUpdateRawMaterialJPanel(userProcessContainer, network, r);
            userProcessContainer.add("SearchUpdateRawMaterialJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

        }
    }//GEN-LAST:event_btnViewRawMaterialActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteRawMaterial;
    private javax.swing.JButton btnSearchRawMaterial;
    private javax.swing.JButton btnViewRawMaterial;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRawMaterialList;
    private javax.swing.JTextField txtRawMaterialID;
    // End of variables declaration//GEN-END:variables
}
