/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NetworkCoordinator;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.NetworkManagementEnterprise;
import Business.Network.Network;
import Business.Network.NetworkCoordinatorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.NetworkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sachinsenthilkumar
 */
public class RequestToNetwork extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private Enterprise enterprise;
    private Network network;
    private Ecosystem system;/**
     * Creates new form RequestToNetwork
     */
   

    public RequestToNetwork(JPanel userProcessContainer, UserAccount useraccount, Enterprise enterprise, Network network, Ecosystem system) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.useraccount=useraccount;
       this.enterprise=enterprise;
       this.network=network;
       this.useraccount=useraccount;
      this.system=system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRequestNetwork = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        message = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Request To Network");

        btnRequestNetwork.setBackground(new java.awt.Color(0, 0, 0));
        btnRequestNetwork.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRequestNetwork.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestNetwork.setText("Request Network");
        btnRequestNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestNetworkActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnRequestNetwork, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addComponent(message, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(351, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(88, 88, 88)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnRequestNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(360, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RequestNetworkPanel rnp = (RequestNetworkPanel) component;
        rnp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRequestNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestNetworkActionPerformed
        // TODO add your handling code here:
        String mess= message.getText();
        
     
     NetworkRequest request=new NetworkRequest() ;
    

        
        request.setSender(useraccount);
        request.setStatus("Sent");
       request.setMessage(mess);
       
        

   
            Organization org = null;
            for(Enterprise e:  network.getEnterpriseDirectory().getEnterpriseList()){
                
                if(e instanceof NetworkManagementEnterprise){
                    
                for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
                    
            if (organization instanceof NetworkCoordinatorOrganization){                                    // Network Requests another network
                org = organization;
                break;
            }
        }}}
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            System.out.println(useraccount);
            useraccount.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(this,"Network Request Created");
        }
        
        
    }//GEN-LAST:event_btnRequestNetworkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField message;
    // End of variables declaration//GEN-END:variables
}
